### ISSUE TITLE
Site feedback design for userreport.com widget

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#102]
You can see it live on staging. We are very limited in what we can customize - color, left/right side, and I don't know if much more. Still, let us know if you'd like to make any change to it. I personally think it looks pretty bad on the map page, but that's just me.

**Comment by juancarlosalonso** [comment]
I think we should move it to the bottom right corner of the page. 
`bottom:12px;
right:0px; 
`
<img width="1280" alt="screen shot 2017-11-27 at 10 26 39" src="https://user-images.githubusercontent.com/20836216/33259555-8624e776-d35d-11e7-8d51-ec2ab770468b.png">

**Comment by tiagojsag** [comment]
https://userreport.com/test/fb-examples/#2

https://helpdesk.userreport.com/hc/en-us/articles/209410026-Disabling-the-feedback-tab

Seems like it's possible to implement custom buttons. However, we want to spend very little time on this, so if you want to do a custom design, please check with @sorodrigo to make sure we have something simple and easy to implement.

**Comment by juancarlosalonso** [comment]
I'm happy with the way it works now. Would be great to change the icon, though.
<img width="363" alt="screen shot 2017-12-01 at 10 52 04" src="https://user-images.githubusercontent.com/20836216/33477365-b6549330-d685-11e7-83c3-ecc805dc63ff.png">

**Comment by tiagojsag** [comment]
yeah, the current icon is rather creepy :P

**Comment by juancarlosalonso** [comment]
the new icon is here: https://www.dropbox.com/s/rpfpko9nxjgtllr/feedback.svg?dl=0
