### ISSUE TITLE
Expand bivariate maps from 9 to 16 buckets - Replace current 9 bucket scale with new 16 colors scale

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#104]
Create the color codes and the  2 dimensions svg legend for the map

**Comment by juancarlosalonso** [comment]
Color codes:
`#F6F5ED, #F5D0B9, #F5928D, #F65E6E, 
#CFE7DF, #C6C6B9, #C18686, #C55966,
#A4D2CF, #91B4B5, #84747A, #864F57,
#8DB6CA, #7F90A4, #635B69, #443537`
following this order:
![screen shot 2017-11-27 at 12 00 28](https://user-images.githubusercontent.com/20836216/33263568-9ca091e6-d36a-11e7-8b88-fc968177fb23.png)

**Comment by juancarlosalonso** [comment]
The svg for the arrows is here: https://www.dropbox.com/s/8eto6gtjqnl00rs/bidimensional-legend-arrows-16.svg?dl=0

**Comment by tiagojsag** [comment]
:+1: thanks @juancarlosalonso , handing it off to the FE team
