### ISSUE TITLE
Return main_node_id on get_all_nodes

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#106]
This is needed to unify nodes in the global search results. This is my proposed solution, but happy to discuss others

**Comment by tiagojsag** [comment]
@sorodrigo this should unblock the global search

**Comment by agnessa** [comment]
@sodrigo this adds `main_node_id`, which is a grouping attribute; same company exporter / importer will have the same value of this attribute. Note this does not link to the `id` of another node, it's a completely different identifier.

**Comment by sorodrigo** [comment]
Perfect thanks!!
