### ISSUE TITLE
Move map zoom to the top left corner

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#120]
https://github.com/Vizzuality/TRASE-frontend/issues/310

Description:
- Move the zoom in/out buttons to the top left corner of the map (see screenshot below)

Test:
- Buttons placement like screenshot below
- Make sure zoom buttons work as intended (they actually zoom in/out)

**Comment by juancarlosalonso** [comment]
Is not validated with SEI but I'm not sure they need to be on top of such a small detail.
The idea is to separate the zoom buttons to make the layers one more prominent.

![screen shot 2017-11-27 at 12 11 35](https://user-images.githubusercontent.com/20836216/33264035-3ba07030-d36c-11e7-96bc-e937dfe0861c.png)

**Comment by tiagojsag** [comment]
https://basecamp.com/1756858/projects/12498794/todos/333060377
