### ISSUE TITLE
Rename factsheets to profile pages

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#122]
- [x] flows -> tool
- [x] factsheets, factsheet-* -> profiles

- [x] add redirections
- [x] strip .html extension
- [ ] remove `pageName` in webpack config

**Comment by tiagojsag** [comment]
https://github.com/Vizzuality/TRASE-frontend/issues/303

**Comment by nerik** [comment]
Should be done along with refactor of the webpack config
