### ISSUE TITLE
Forest code deficit has values larger than specified maximum

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#125]
"Recolor by" forest code deficit is configured to range between 0 ans 22%, but some values are larger than 22.

We need a new scale with 1 more color, to represent 22-24%

**Comment by tiagojsag** [comment]
See also https://basecamp.com/1756858/projects/12498794/todos/328790730

**Comment by tiagojsag** [comment]
@juancarlosalonso can we have a new color scale here, please? thanks

**Comment by juancarlosalonso** [comment]
Let's add `#6f001a` please

**Comment by tiagojsag** [comment]
we need to:

- [ ] Add new color to the FE
- [ ] Update the database max value
