### ISSUE TITLE
Weird "legend" appearing on scatter plot

### ISSUE THREAD

**Issue by juancarlosalonso** [Vizzuality/trase#138]
In the scatterplot of the actor profiles:
- [x] remove the "Land use [Ha]" label  
- [ ] change the "Trade Volume (Kiloton)" to "Trade Volume (kT)"
- [ ] change "Kiloton" to "kT" in the tooltips

**Comment by tiagojsag** [comment]
do the first, @juancarlosalonso  add the other two to BC for discussion, as this was recently discussed with Lena

**Comment by tiagojsag** [comment]
https://basecamp.com/1756858/projects/12498794/todos/334102802#comment_582524204

**Comment by tiagojsag** [comment]
Fixed by https://github.com/Vizzuality/trase/pull/209, closing
