### ISSUE TITLE
Add team page with photos and bios

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#149]
https://app.zeplin.io/project/5a017b22d882ec6e04009065/screen/5a0ecf9ffbe8345d41ac91b6
https://app.zeplin.io/project/5a017b22d882ec6e04009065/screen/5a79672e13c3d6532003302e

See also https://basecamp.com/1756858/projects/12498794/todos/327055905#comment_596566519

Description
- Implement bio list and bio detail pages, as per design above
- API will provide a list of groups, with a "position" to define order
- API will provide a list of bios to show on the list page, with the associated groups (can be in the same endpoint as above)
- Let's discuss if we need an endpoint to load the details of a single bio page. I expect the above endpoint will not be very complex or generate a large response, so maybe we can use it for everything?
- Backend needs to define priority for groups and for people inside groups, and FE needs to respect that
- Support picture upload (required field)

Test:
- Bio page should describe staff with categories and picture
- Test with fresh load of each page, as well as access from other pages. test both detail and list pages

**Comment by tiagojsag** [comment]
Not sure if we have design approved for this yet, based on the new homepage redesign

**Comment by juancarlosalonso** [comment]
Please find the design here: https://invis.io/FREOO4UJB#/268271103_2_About_-_Team

**Comment by tiagojsag** [comment]
Do we have these on zeplin?

**Comment by tiagojsag** [comment]
http://zpl.io/a30lREd

**Comment by tiagojsag** [comment]
There are multiple ways to implement this:
- API serves the data
- Frontend keeps data in easy to edit files (for example, Json files) that can be easily manipulated
- Hardcoded, like current "about" page and such

@agnessa @sorodrigo let's discuss

**Comment by tiagojsag** [comment]
Design presented, waiting approval

**Comment by tiagojsag** [comment]
API bit merged, frontend missing
