### ISSUE TITLE
Map: Integrating multiple years of data for map layers

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#150]
We currently support this for single years, need to expand to multiple year, by adding aggregation logic.

Description:
When a user loads a map layer for multiple years, they should see data aggregated for that time period (aggregation logic will depend on the metric). We also need to think about the cases when data is not available for all years selected, on which scenario the user should be informed. The legend below the map should also reflect the aggregated scale of the data

Test
- Selecting single years of data on the map should show plain values (current behavior)
- Selecting multiple years of data on the map should show aggregated values
- Selecting multiple years of data on the map should update legend to match new range (depending on aggregation logic)
- Selecting two dimension choropleth should show aggregated data and legend on both dimensions
- User should be informed in case only partial data is available in any scenario.

**Comment by agnessa** [comment]
The changes required from the API are these I suppose:
- in the `map_layers` endpoint:
    - we already allow `year_start` and `year_end` parameters but we need to apply them correctly
    - `dimensionGroups` - no change
    - `dimensions`: In terms of the response structure I don't think anything needs to change; but we need to serve aggregated values for `dualLayerBuckets` and `singleLayerBuckets`. The type of aggregation is already given as `aggregateMethod` - it's `SUM` for quants and `AVG` for inds, but it is not currently applied to bucket values. There already is a `years` array (when it's null it means data present for all years available for context)
    - `contextualLayers`:  this needs changes to support data for different years. There was a discussion about that here: https://github.com/Vizzuality/TRASE-frontend/issues/490 - I believe a good solution was proposed.

- in the `nodes/attributes` endpoint
    - we already allow `start_year` and `end_year` parameters but we need to apply them correctly (I would change the names of these parameters though, so that for every request that supports them they're the same - `flows`, `linked_nodes`, `map layers`, `nodes/attributes`, `top_nodes`)
    - we need to make sure the aggregated multi year values are classified into aggregated multi year buckets, which is not in place right now
    - this endpoint is very slow. It would make sense to me to split it by map attribute - so for each map attribute as returned in `dimensions` in `map_layers` there would be a separate request. Would it work front-end-wise?

@tiagojsag @sorodrigo

**Comment by sorodrigo** [comment]
> we already allow start_year and end_year parameters but we need to apply them correctly

I agree on changing the param names to be uniform across all endpoints.

> this endpoint is very slow. It would make sense to me to split it by map attribute - so for each map attribute as returned in dimensions in map_layers there would be a separate request.

So how would this work frontend-wise?

**Comment by agnessa** [comment]
Could it be fetched when user actually enables a particular layer on the map, or is it needed earlier?

**Comment by sorodrigo** [comment]
> contextualLayers: this needs changes to support data for different years. There was a discussion about that [..] I believe a good solution was proposed.

I agree

> Could a single map attributes values be fetched when user actually enables a particular layer on the map, or is it needed earlier?

I'll get back to you on that one 😅

**Comment by tiagojsag** [comment]
I have it on my todo list to load the map attributes when the user selects the corresponding layers. This should help with performance and scalibility too. but, if it makes sense/needs to be done as part of this issue, that's also fine for me

**Comment by sorodrigo** [comment]
> Let's have rodrigo do my job
