### ISSUE TITLE
Move map/sankey selection "pills"

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#152]
When seeing a filtered map view, we need to identify which node filters are in place

**Comment by juancarlosalonso** [comment]
![tool zoomed out](https://user-images.githubusercontent.com/20836216/33894527-812a4bc8-df5e-11e7-9f17-b2f32ba82f18.png)

The new placement of the pills in the bottom would make them appear when the map is open, therefor improving the labelling and solving this.
