### ISSUE TITLE
Enable/disable choropeth per column

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#153]
When viewing states and biomes (column 1) the shapefiles on the map do not display choropleth (even though legend remains in place). If not possible to implement immediately it would be better to have map layer automatically deselect.

Following on the conversation on https://basecamp.com/1756858/projects/12498794/todos/327056004
we agreed to limit choropleth to certain columns. We need to factor this into the DB/API first, and onto the FE after

Test:
- Choropleth layer should hide/show depending on selected first column on the sankey
- Changing columns to a "no choropleth" value should reset any previously selected value on the choropleth layers.

**Comment by agnessa** [comment]
#240

**Comment by tiagojsag** [comment]
#240 merged, so API work is done, frontend fun time.
