### ISSUE TITLE
Data Portal: More advanced conditional queries (e.g. imports to France in Year X and greater than Y tonnes)

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#176]
https://basecamp.com/1756858/projects/12498794/todos/327056269

Currently pending clearer definition

MUST. USE. THE. RIGHT. ICON.

**Comment by agnessa** [comment]
Can we agree on query params style to support the filters? There are two which come to my mind, both simple to handle in the backend so happy to go with whichever works better for frontend.

1. indexed array `download.csv?attrs[1][name]=FOB&attrs[1][op]=lt&attrs[1][val]=2&attrs[2][name]=Volume&attrs[2][op]=eq&attrs[2][val]=5&attrs[3][name]=SOY_YIELD`

The indexes are used to logically group the name of indicator, the comparison operator and the value for comparison, therefore order does not matter. They can be sequential numbers of no other significance than to group the params - their values don't affect the filtering.

Rails parses this into: `"attrs"=>{"1"=>{"name"=>"FOB", "op"=>"lt", "val"=>"2"}, "2"=>{"name"=>"Volume", "op"=>"eq", "val"=>"5"}, "3"=>{"name"=>"SOY_YIELD"}`

2. unindexed array `download.csv?attrs[][name]=FOB&attrs[][op]=lt&attrs[][val]=2&attrs[][name]=Volume&attrs[][op]=eq&attrs[][val]=5&attrs[][name]=SOY_YIELD`

In this representation order of query params matters. Rails decides to start accumulating values in a new hash whenever it encounters an input name that already exists in the current hash.

Rails parses this into:  `"attrs"=>[{"name"=>"FOB", "op"=>"lt", "val"=>"2"}, {"name"=>"Volume", "op"=>"eq", "val"=>"5"}, {"name"=>"SOY_YIELD"}`

/cc @sorodrigo

**Comment by agnessa** [comment]
backend: https://github.com/Vizzuality/trase/pull/320
