### ISSUE TITLE
Landing page: implement backend support for new content structure

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#178]
- [x] "Category" field (insights, news, etc) for the already existing stories
- [x] New "Testimonials" endpoint: with "quote", "author name", "author title" and "author pic"
- [x] On tweets, return avatar url/img
- [x] "Starred" flag on stories: limit to 1 (reuse highlighted). When a admin highlights a post, de-highlight any previously highlighted posts
- [x] potentially new types of content for "insights" (https://basecamp.com/1756858/projects/12498794/messages/73758553)
- [x] Remove "content" field from post content type
- [x] Remove logic that loads different images based on highlighted flag
- [x] Add a "type of link" select, with "file" or "webpage"

**Comment by tiagojsag** [comment]
- "Category" field (insights, news, etc) for the already existing stories
- New "Testimonials" endpoint: with "quote", "author name", "author title" and "author pic"
- On tweets, return avatar url/img
- "Starred" flag on stories: limit to 1

**Comment by tiagojsag** [comment]
"Testimonials" done on https://github.com/Vizzuality/trase/pull/210

**Comment by agnessa** [comment]
frontend https://github.com/Vizzuality/trase/issues/212
