### ISSUE TITLE
Database consolidation: Validation service allowing to verify the consistency of the entire dataset (data tables and visualisation tables)

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#185]
Description
- Build a basic validation framework for data
- Should validate sanity of data of blue tables, yellow tables, and the intersection between the two.
- Output can be a plain json or similar.
- Currently, the tests should be few and simple. I think it's best if we focus on the basic now, and add as we move along (happy to discuss this if you want)
- (optional) build a very basic UI that allows a human to run this task, and see the resulting JSON

Test
- We have a basic but extendable framework to test database inconsistencies
- The current validation endpoint has basic tests, that we can easily extend in the future
- The validation endpoint can be called at any point during the application life cycle (right after db import, or later on)

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/312
