### ISSUE TITLE
Adjust summary on profile pages of small producers

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#249]
See https://basecamp.com/1756858/projects/12498794/todos/332904512

On profiles like https://staging.trase.earth/profile-place?nodeId=1954&year=2015 where it says "With 0.00% of ..." we should use "With less than 0.01% of ..."

Test
- Small producers have the message above
- Large producers are unaffected.

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/291
