### ISSUE TITLE
Add contraints to database on resize_by and recolor_by per context

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#251]
Just spent 1h looking for a "frontend" bug that turns out to be a database bug (aren't all bugs really a database bug?). 
In any case, my bug is that https://staging.trase.earth/api/v3/contexts returns no isDefault = true for the recolor_by of context with id 1. So, we should enforce that each context should have one and one only default recolor_by and a default resize_by. If enforcing is not possible, we should look to other options

**Comment by agnessa** [comment]
It's easy to enforce that it has no more than one on database level. I guess enforcing that it has 1 exactly is trickier, as the trigger would need to be on insert / update to `context_properties`, and these operations happen outside of the import process; I thing a good place for that check will be within the validation endpoint.

**Comment by tiagojsag** [comment]
I need to review this, because I think we can actually have no default recolor by, but I think we need a resize by. I'll reopen this once I have more info

**Comment by agnessa** [comment]
I guess what should happen in such case is that a context without a default resize by should not be returned at all in the contexts call; we might have more cases like that where missing "yellow table" information has a potential of breaking the site, and I would opt for a  "report in validation script" + "suppress on frontend" approach.

**Comment by tiagojsag** [comment]
yeah, we need to discuss what's the best way to inform everyone in case this happen, so it doesn't become a "we have a bug on the site" kind of situations
