### ISSUE TITLE
Review menu structure on static content pages

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#252]
https://basecamp.com/1756858/projects/12498794/messages/73758553#comment_592266252

Description:
- Change links on sidenav to the definition from link above
- Update top level navigation to include nested links in the "about" section (see definition above)

Test
- Links should have the names from the above link
- Static root level pages should be nested inside "about"
- Top menu should highlight root level element when the page is a nested one

**Comment by sorodrigo** [comment]
_"What is the vision of Trase?"_ texts references a link, but none is included.
