### ISSUE TITLE
Markdown editor for static pages

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#284]
Description
- Use the current .md editor we already have on rails land to also power the static pages: about and friends
- Create an API endpoint to serve this .md content.
- Things like title and such don't need to go on the API/DB
- The list of pages will be hardcoded in the FE for now, possibly made flexible in a future development phase
- The FE should only need minor change to use it

Tests
- Make sure that content edits in the BE are reflected in the FE
- Test new page loads and and entry from other pages.

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/294
