### ISSUE TITLE
Styling tweaks

### ISSUE THREAD

**Issue by juancarlosalonso** [Vizzuality/trase#341]
**Homepage**
- [x] featured blog card - `background-size:cover` needed for the image
- [x] the arrows are weirdly positioned, and they get cut when the screen is small, `.slide-prev` should have `transform: translateX(100%);` and `.slide-next` should have `transform: translateX(-100%);`
- [ ] use smaller images for entrypoints on mobile.

**About**
- [x] background should be #f6f6f6

**Profile Search**
- [x] `.profile-search-bar` should have `padding: 2px 16px 0 0;` and `border-radius: 4px;`
- [x] `.profile-search-input` should have `padding: 0 5px 0 20px;`

**Profiles**
- [x] `.icon-download-pdf` should have `height: 25px;`

**Global map**
- [x] `.dimensional-selector-footer-text` should have `font-weight: 500;`

**Sankey**
- [x] `.leaflet-control-zoom` should have `box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.2);` and `border-radius: 4px;`
- [x] Scale gets cut when two layers are active

**Comment by tsubik** [comment]
Homepage issues addressed [here](https://github.com/Vizzuality/trase/pull/344).

**Comment by sorodrigo** [comment]
We need smaller images for the mobile entrypoints @juancarlosalonso . For now, I'm leaving it with the current images but would be cool to change them next week.

**Comment by tsubik** [comment]
@juancarlosalonso not sure what is "Scale gets cut" about. @sorodrigo maybe you know what is the problem?

**Comment by sorodrigo** [comment]
@tsubik I made a fix in your branch for the scale and the tooltips appearing above nav.
