### ISSUE TITLE
Reassess cache expiration time

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/trase#393]
https://github.com/Vizzuality/trase/blob/595eed671ab892bea15ad1912ba77c3f0bc59486/app/controllers/application_controller.rb#L28

On second thoughts I wonder if:
- maybe would be better to have s-maxage higher than maxage, as that is the one Varnish will use
- maybe would make sense to have the same settings for staging and production at least now that you're doing performance testing of the frontend

**Comment by tiagojsag** [comment]
Just realized we are being dumb. We have HTTP/2, which means we have SSL always on, which means no public caches. I would raise the s-maxage to hours instead of minutes

**Comment by agnessa** [comment]
OK I do feel dumb ;) So you think Varnish is actually the only thing that will  read the s-maxage? If that is the case it makes sense to increase it. Perhaps worth monitoring the current hit rate to set a healthy timeout and the best thing to do is leave it at 2 hours as it used to be and keep observing that.

**Comment by agnessa** [comment]
https://github.com/Vizzuality/trase/pull/399
