### ISSUE TITLE
Permanently warm cache for top profile pages - figure out

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/trase#402]

**Comment by agnessa** [comment]
For simplicity let's define top profile pages as "top 10 nodes on the 1st column of the sankey" (places) and "top 10 nodes on the 2nd column of the sankey" (actor) for Brazil-soy 2015. We can:
- generate and keep a static list of these urls
- allow users to decide which nodes make it to the list
I guess I'd go with the first option at this stage.

With a list like that the most common approach for Varnish seems to be a cron task that periodically wgets / curls the urls, e.g. like here: https://blog.theodo.fr/2015/11/auto-warm-up-varnish4-cache/

What is often also practiced, and what I think would make a lot of sense, is to keep the list of the urls to hit in form of a sitemap and use a script like this one: https://github.com/sys0dm1n/varnish-cache-warmer Currently profiles are not discoverable in search engines and a sitemap would help, so 2 benefits in one.

Thoughts @tiagojsag @tsubik ?

**Comment by tsubik** [comment]
Any kind of cache warming solutions would be very beneficial :+1: . I think simple static text file with URLs would be enough and we should not force refresh the cache as described in that blog post.

**Comment by agnessa** [comment]
Agreed, we don't need to force refresh as we have built-in purging.

**Comment by tsubik** [comment]
Maybe we should re-cache the purged content too? I'm not sure how currently purging works, but I'm guessing that the cache is empty after that.

**Comment by tiagojsag** [comment]
We can start by just warming up the cache on deploy/database update. We can explore warming it up also when it's purged by an edit on the admin side of things, but that should happen mostly on staging, not on prod, so I'm not super concerned about it.
