### ISSUE TITLE
Support multi-year on sankey flows

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#425]
Have the sankey code request multiple years of flows data from the API, and render that
Also include whatever changes are needed in resize_by and recolor_by

**Comment by sorodrigo** [comment]
Ok, I tested multiple years in different contexts and with different resize_by + recolor_by and it seems to _just work_ so I'm going to get started with the map.

**Comment by tiagojsag** [comment]
Let's carefully test this, stuff that "just works" usually means we need to be more careful around edge cases and other things
