### ISSUE TITLE
Support multi-year on map choropeth

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#426]
We currently support this for single years, need to expand to multiple year, by adding aggregation logic.

Description:
When a user loads a map layer for multiple years, they should see data aggregated for that time period (aggregation logic will depend on the metric). We also need to think about the cases when data is not available for all years selected, on which scenario the user should be informed. The legend below the map should also reflect the aggregated scale of the data

Test
- Selecting single years of data on the map should show plain values (current behavior)
- Selecting multiple years of data on the map should show aggregated values
- Selecting multiple years of data on the map should update legend to match new range (depending on aggregation logic)
- Selecting two dimension choropleth should show aggregated data and legend on both dimensions
- User should be informed in case only partial data is available in any scenario.

**Comment by agnessa** [comment]
Is this different from https://github.com/Vizzuality/trase/issues/150?

There's an open PR: https://github.com/Vizzuality/trase/pull/421

**Comment by tiagojsag** [comment]
API is merged, only FE missing

**Comment by tiagojsag** [comment]
Duplicated of https://github.com/Vizzuality/trase/issues/150
