### ISSUE TITLE
Compile list of values the validation tool could suggest to the user

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/trase#432]
These are the calculations that I believe we could do automatically after copying data from the main db, by table:

`contexts`
- years - calculated from flows
- default_year - most recent year of data

`download_attributes`
- years - calculated from flow attributes

`map_attributes`
- years - calculated from node attributes
- double _layer_buckets - calculated from data
- single_layer_buckets - this is variable length, but the default will be 5 buckets (4 values), so we could calculate bucket values from data

`recolor_by_attributes`
- years
- max / min value

`resize_by_attributes`
- years

`ind / qual / quant_properties`
- is_temporal - possibly could be inferred from flow / node attributes

`node_properties`
- is_domestic_consumption - we could try to infer by name

**Comment by agnessa** [comment]
I assume this is for next phase, but this is the list of things that I think we could pre-calculate as I see it now.

**Comment by tiagojsag** [comment]
Yes, this is for the next phase, we just want to start compiling a list, but this is not a priority task

**Comment by agnessa** [comment]
The list in the description is all I can think of for now.

**Comment by tiagojsag** [comment]
https://basecamp.com/1756858/projects/12498794/todos/348927607
