### ISSUE TITLE
The year cannot be changed for any of the contexts available

### ISSUE THREAD

**Issue by pablopareja** [Vizzuality/trase#452]
![image](https://user-images.githubusercontent.com/545342/38860668-06e69c14-4231-11e8-89b4-5ddb10d6ec6f.png)

https://trase.earth/explore?contextId=1

I tried with most of the combinations and none of them seem to work.

> The trace shown in the screenshot is probably unrelated to the bug -it seems to be thrown when loading the homepage-

**Comment by tiagojsag** [comment]
Cannot reproduce - I can change the year just fine

**Comment by tsubik** [comment]
Maybe the problem is that you have to drag this little "window", clicking on year does not work which may be confusing. Anyway, a new multi year selector will replace that component.

**Comment by pablopareja** [comment]
Yeah, Rodrigo told me about this yesterday. I would have never thought that it was a draggable selector... 😳 😅 
I'll close the issue 👍
