### ISSUE TITLE
Mobile Profile page issues.

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/trase#457]
1. Spinner should be below nav bar.
2. Lines in charts have too similar colors.
<img width="375" alt="spinner" src="https://user-images.githubusercontent.com/12124839/38927226-5c146a2a-4305-11e8-8e7b-bb91938df5ac.png">
<img width="375" alt="chart" src="https://user-images.githubusercontent.com/12124839/38927227-5c2dfcb0-4305-11e8-824f-563a0dc22253.png">

**Comment by tsubik** [comment]
Yeah, I agree, the line color is taken from the buckets. It was fine when lines are clearly labeled as it happens on higher resolution. Here we have to come up with some extra color scale.

**Comment by tsubik** [comment]
It makes sense if spinner position is fixed on the profile page, always in the center of the screen.
