### ISSUE TITLE
Finalize styleguide

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#459]
From Andrea's email from April 12th:

Visual ID:

Please add the light gray color to the color palette we are working with

 

PPT:

Please change the format so all slides use the full breadth of the slide and not just half. (this would also be applied even in the visual ID document)  I mentioned this before and won’t approve a ppt template where those using can only use half the slide. I would be sent to the slaughter house.

**Comment by tiagojsag** [comment]
@juancarlosalonso can we close this?

**Comment by juancarlosalonso** [comment]
I think so, yes.
