### ISSUE TITLE
biome_geoid column needed in the CARTO municipalities table

### ISSUE THREAD

**Issue by nerik** [Vizzuality/trase#76]
In order to filter municipalities by biome in the frontend, we need an additional `biome_geoid` column in the CARTO municipalities table.

Municipalities table:
https://sei-international.carto.com/u/p2cs-sei/dataset/brazil_municipalities_1

Biomes table:
https://sei-international.carto.com/u/p2cs-sei/dataset/brazil_biomes

This could be done by doing a spatial join on both table's `the_geom`

**Comment by guizar** [comment]
The `biome_geoid` column in the municipalities table is now showing biomes id values:

https://sei-international.carto.com/u/p2cs-sei/dataset/brazil_municipalities_1

Some of the Pantanal municipalities (`BR6`) are not showing the correct biome information. I'll have a look to correct this issue

**Comment by guizar** [comment]
The above issue has been solved

**Comment by sorodrigo** [comment]
Hey @guizar we found some issues with the municipalities located near the biome borders. We'll need to refine the query to include the municipalities in the biome that has the largest part in it.
Thanks!
![screen shot 2017-11-22 at 16 29 36](https://user-images.githubusercontent.com/12124839/33135449-b4907ea4-cfa2-11e7-8c50-ef44be396f46.png)

**Comment by guizar** [comment]
thanks for pointing this @sorodrigo. I refined the query as suggested above and the allocation of biome labels is now much more improved
