### ISSUE TITLE
Inspect odd smelly node

### ISSUE THREAD

**Issue by sorodrigo** [Vizzuality/trase#88]
Found this in the nodes:
![screen shot 2017-11-22 at 19 06 18](https://user-images.githubusercontent.com/12124839/33143175-5422710a-cfb9-11e7-9d4c-5422946ea016.png)

**Comment by nerik** [comment]
In case you wonder, `name` is weird

**Comment by tiagojsag** [comment]
not sure why this is assigned to Agnieszka, I think it makes more sense to talk to Clement about this

**Comment by agnessa** [comment]
Just checked, this comes out like this from database, worth flagging. Maybe a candidate for the is_unknown flag?

**Comment by csuavet** [comment]
This is directly coming from the raw data files. It was probably a mistake, but there isn't much we can do, so let's keep it that way.

**Comment by tiagojsag** [comment]
ok, closing
